services:
  db:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5000"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:5001"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:5002"
    depends_on:
      - backend
  webserver:
    container_name: webserver
    image: proxy
    build: ./webserver
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
